<?php

namespace CoreBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
  public function getArticlesImagesAndCategories() {
    $articles = $this->createQueryBuilder('a')
    ->orderBy("a.id", "DESC")
    ->setMaxResults(5)
    ->leftJoin("a.image", "img")
    ->addSelect("img")
    ->leftJoin("a.categories", "cat")
    ->addSelect("cat")
    ->getQuery()
    ->getResult();

    return $articles;
  }

  public function getArticlesImagesByModule($module) {
    $articles = $this->createQueryBuilder('a')
    ->where("a.module = " . $module)
    ->leftJoin("a.image", "img")
    ->addSelect("img")
    ->leftJoin("a.categories", "cat")
    ->addSelect("cat")
    ->getQuery()
    ->getResult();

    return $articles;
  }
}
