<?php

namespace CoreBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
  public function getCategoryWithArticles($category) {
    $categoryArticles = $this->createQueryBuilder('c')
    ->where('c.name = :category')
    ->setParameter('category', $category)
    ->leftJoin("c.articles", "art")
    ->addSelect("art")
    ->leftJoin("art.image", "img")
    ->addSelect("img")
    ->getQuery()
    ->getResult();

    return $categoryArticles;
  }
}
