<?php

namespace CoreBundle\Repository;

/**
 * ModuleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModuleRepository extends \Doctrine\ORM\EntityRepository
{
  public function getModulesWithArticles($pathId) {
    $modules = $this->createQueryBuilder('m')
    ->where("m.path = " . $pathId)
    ->leftJoin("m.articles", "art")
    ->addSelect("art")
    ->getQuery()
    ->getResult();

    return $modules;
  }
}
