<?php

namespace CoreBundle\Repository;

/**
 * PathRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PathRepository extends \Doctrine\ORM\EntityRepository
{

  public function getPathTitles() {
    $names = $this->createQueryBuilder('p')
                  ->select('p.title');
    $names = $names->getQuery()->getResult();

    return array_column($names, 'title');
  }

}
