<?php

namespace CoreBundle\Repository;

/**
 * PathRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PathRepository extends \Doctrine\ORM\EntityRepository
{
  public function getPathsWithModules() {
    $paths = $this->createQueryBuilder('p')
    ->leftJoin("p.modules", "mod")
    ->addSelect("mod")
    ->getQuery()
    ->getResult();

    return $paths;
  }
}
