<?php

namespace CoreBundle\Repository;

/**
 * TestBlocRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestBlocRepository extends \Doctrine\ORM\EntityRepository
{
}
